
remote_theme: raviriley/agency-jekyll-theme

url    : "https://kyleburke.tech" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog


title           : Kyle Burke
subtitle        : Subtitle
phone           : (555) 555-5555
functionalPhone : "555555555"
email           : kyle@kyleburke.tech #this is also the email contact forms will go to
author          : Kyle Burke
# formspree_form_path: moqpykav
# logo:     #optional, defaults to site title
  # path: assets\img\logo.webp
  # height: 60 #height in px, defaults to 52px

google:
  #analytics:  #Google Analytics tracking code here
  #ads: 
  #tagmanager: 

sass:
    style: compressed

collections:
  services:
    layout: service
    output: true
    permalink: /:name

markdown: kramdown

plugins:
  - jekyll-remote-theme